---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-tools-image
spec:
  workspaces:
  - name: source
    mountPath: /source
  params:
  - name: repo-path
    description: The path to the repository
  - name: tls-verify
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    default: "true"
  - name: tools-image-url
    type: string

  steps:
  - name: build-and-push-tools
    image: quay.io/buildah/stable:v1.11.0
    workingDir: '$(workspaces.source.path)/$(params.repo-path)/'
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 500m
        memory: 2500Mi
    script: |
      #!/bin/sh
      set -ex
      buildah bud --tls-verify=$(params.tls-verify) --layers -f $(workspaces.source.path)/$(params.repo-path)/openshift-ci/Dockerfile.tools -t $(params.tools-image-url) .
      buildah push --tls-verify=$(params.tls-verify) $(params.tools-image-url) docker://$(params.tools-image-url)

  volumes:
  - name: varlibcontainers
    emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-project
spec:
  workspaces:
  - name: source
    mountPath: /source
  params:
  - name: repo-revision
    description: The git revision
  - name: repo-path
    description: The path to the repository
  - name: tls-verify
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    default: "true"
  - name: tools-image-url
    type: string
  - name: binary-image-url
    type: string

  steps:
  - name: make-build
    securityContext:
      privileged: true
    workingDir: '$(workspaces.source.path)/$(params.repo-path)/'
    image: $(params.tools-image-url)
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
    script: |
      #!/bin/sh
      set -ex
      make build

  - name: build-and-push-image
    image: quay.io/buildah/stable:v1.11.0
    workingDir: '$(workspaces.source.path)/$(params.repo-path)/'
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
    script: |
      #!/bin/sh
      set -ex
      SHORT_SHA=`head -c 7 <<< $(params.repo-revision)`
      buildah bud -t $(params.binary-image-url):${SHORT_SHA} --tls-verify=$(params.tls-verify) --layers -f ./build/Dockerfile .
      buildah push --tls-verify=$(params.tls-verify) $(params.binary-image-url):${SHORT_SHA} docker://$(params.binary-image-url):${SHORT_SHA}

  volumes:
  - name: varlibcontainers
    emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-and-push-csv
spec:
  workspaces:
  - name: source
    mountPath: /source
  params:
  - name: repo-revision
    description: The git revision
  - name: repo-path
    description: The path to the repository
  - name: quay-namespace
    description: The quay namespace CSV should be pushed to
  - name: tools-image-url
    type: string
  steps:

  - name: csv
    securityContext:
      privileged: true
    workingDir: '$(workspaces.source.path)/$(params.repo-path)/'
    image: $(params.tools-image-url)
    command: ["make"]
    args: ["push-to-quay-nightly", "QUAY_NAMESPACE=$(params.quay-namespace)"]


  volumes:
  - name: varlibcontainers
    emptyDir: {}
