---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-pusher
secrets:
- name: push-to-quay-secret
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildah-short-sha-image
spec:
  type: image
  params:
  - name: url
    value: quay.io/matousjobanek/buildah-short-sha:0.1
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: toolchain-cd-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/codeready-toolchain/toolchain-cicd.git
