---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: toolchain-cd-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/codeready-toolchain/toolchain-cicd.git
