---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: toolchain-pipeline-cd-triggertemplate
#  namespace: toolchain-pipeline-cd
spec:
  params:
  - name: git-revision
    description: The git revision
    default: master
  - name: repo-name
    description: The repository name
  - name: full-repo-name
    description: The full repository name
  - name: clone-url
    description: The git clone url of the repo
#  - name: namespace
#    description: The namespace to create the resources

  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: binary-image-$(params.repo-name)-$(uid)
#      namespace: $(params.namespace)
    spec:
      type: image
      params:
      - name: url
        value: quay.io/matousjobanek/$(params.repo-name)
#        value: quay.io/$(params.full-repo-name)

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: repo-$(params.repo-name)-$(uid)
#      namespace: $(params.namespace)
    spec:
      type: git
      params:
      - name: url
        value: $(params.clone-url)
      - name: depth
        value: '0'

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: tools-image-$(params.repo-name)-$(uid)
#      namespace: $(params.namespace)
    spec:
      type: image
      params:
      - name: url
        value: quay.io/matousjobanek/$(params.repo-name)-tools:latest
#        value: quay.io/$(params.full-repo-name)-tools:latest

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: toolchain-cd-pipeline-run-$(uid)
#      namespace: $(params.namespace)
    spec:
      pipelineRef:
        name: build-csv
      params:
      - name: repo-name
        value: $(params.repo-name)
      - name: git-revision
        value: $(params.git-revision)
      - name: repo-path
        value: 'go/src/github.com/codeready-toolchain/$(params.repo-name)'
      - name: quay-namespace
        value: matousjobanek
      resources:
      - name: project-repo
        resourceRef:
          name: repo-$(params.repo-name)-$(uid)
      - name: tools-image
        resourceRef:
          name: tools-image-$(params.repo-name)-$(uid)
      - name: binary-image
        resourceRef:
          name: binary-image-$(params.repo-name)-$(uid)
      - name: toolchain-cd-repo
        resourceRef:
          name: toolchain-cd-repo
      - name: buildah-short-sha-image
        resourceRef:
          name: buildah-short-sha-image
      serviceAccountName: image-pusher
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: toolchain-pipeline-cd-pipelinebinding
#  namespace: toolchain-pipeline-cd
spec:
  params:
  - name: git-revision
    value: "$(body.head_commit.id)"
#  - name: namespace
#    value: toolchain-pipeline-cd
  - name: repo-name
    value: "$(body.repository.name)"
  - name: full-repo-name
    value: "$(body.repository.full_name)"
  - name: clone-url
    value: "$(body.repository.clone_url)"
