apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolchain-cd-sync-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: toolchain-cd-sync-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: toolchain-cd-sync-sa