---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-pusher
secrets:
- name: push-to-quay-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
secrets:
- name: push-to-quay-secret
