# This file contains ServiceAccount and its Role and RoleBindings necessary to be able to update/create all pipeline resources from this repository
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolchain-cd-sync-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: toolchain-cd-sync-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: toolchain-cd-sync-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    provider: codeready-toolchain
  name: rbac-edit
rules:
- apiGroups:
  - authorization.openshift.io
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    provider: codeready-toolchain
  name: toolchain-cd-sync-rbac-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-edit
subjects:
- kind: ServiceAccount
  name: toolchain-cd-sync-sa