---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-resources-task
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: PATHTODEPLOYMENT
      type: string
      description: Path to the manifest to apply
      default: deploy
    - name: DRYRUN
      type: string
      description: If true run a server-side dryrun.
      default: "false"
  steps:
  - name: run-oc-apply
    image: quay.io/openshift/origin-cli:4.3
    workingDir: /workspace/source
    command: ["oc"]
    args:
    - "apply"
    - "--dry-run=$(inputs.params.DRYRUN)"
    - "-f"
    - "$(inputs.params.PATHTODEPLOYMENT)"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-resources-task
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: PATHTODEPLOYMENT
      type: string
      description: Path to the manifest to apply
      default: deploy
    - name: DRYRUN
      type: string
      description: If true run a server-side dryrun.
      default: "false"
  steps:
  - name: run-oc-apply
    image: quay.io/openshift/origin-cli:4.3
    workingDir: /workspace/source
    command: ["oc"]
    args:
    - "create"
    - "--dry-run=$(inputs.params.DRYRUN)"
    - "-f"
    - "$(inputs.params.PATHTODEPLOYMENT)"