---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-resources-task
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: path-to-deployment
      type: string
      description: Path to the manifest to apply
      default: deploy
    - name: dry-run
      type: string
      description: If true run a server-side dryrun.
      default: "false"
    - name: namespace-name
      type: string
      default: ""
    - name: oc-command
      type: string
      default: "apply"
  steps:
  - name: run-oc-apply
    image: quay.io/openshift/origin-cli:4.3
    workingDir: /workspace/source
    script: |
      #!/bin/sh
      set -ex
      if [[ -z "$(inputs.params.namespace-name)" ]]; then
        NAMESPACE=`oc project`
      else
        NAMESPACE=$(inputs.params.namespace-name)
      fi
      oc $(inputs.params.oc-command) --dry-run=$(inputs.params.dry-run) -f $(inputs.params.path-to-deployment) -n ${NAMESPACE}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: process-project-and-apply-task
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: path-to-deployment
      type: string
      description: Path to the manifest to apply
      default: deploy
    - name: dry-run
      type: string
      description: If true run a server-side dryrun.
      default: "false"
    - name: namespace-name
      type: string
      default: ""
    - name: oc-command
      type: string
      default: "apply"
  steps:
  - name: run-oc-apply
    image: quay.io/openshift/origin-cli:4.3
    workingDir: /workspace/source
    script: |
      #!/bin/sh
      set -ex
      if [[ -z "$(inputs.params.namespace-name)" ]]; then
        NAMESPACE=`oc project`
      else
        NAMESPACE=$(inputs.params.namespace-name)
      fi
      for REPO in `cat toolchain-cd-projects`; do
        oc process -f $(inputs.params.path-to-deployment) -p TOOLCHAIN_REPO=${REPO} | oc $(inputs.params.oc-command) --dry-run=$(inputs.params.dry-run) -n ${NAMESPACE} -f -
      done
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: process-all-projects-and-create-task
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: path-to-deployment
      type: string
      description: Path to the manifest to apply
      default: deploy
    - name: dry-run
      type: string
      description: If true run a server-side dryrun.
      default: "false"
    - name: namespace-name
      type: string
      default: ""
    - name: oc-command
      type: string
      default: "create"
  steps:
  - name: run-oc-apply
    image: quay.io/openshift/origin-cli:4.3
    workingDir: /workspace/source
    script: |
      #!/bin/sh
      set -ex
      if [[ -z "$(inputs.params.namespace-name)" ]]; then
        NAMESPACE=`oc project`
      else
        NAMESPACE=$(inputs.params.namespace-name)
      fi
      ALL_PROJECTS=`cat toolchain-cd-projects | tr "\n" " "`
      oc process -f $(inputs.params.path-to-deployment) -p TOOLCHAIN_CD_PROJECTS="${ALL_PROJECTS}" | oc $(inputs.params.oc-command) --dry-run=$(inputs.params.dry-run) -n ${NAMESPACE} -f -