apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: toolchain-cd-sync-task
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: PATHTODEPLOYMENT
      type: string
      description: Path to the manifest to apply
      default: deploy
    - name: DRYRUN
      type: string
      description: If true run a server-side dryrun.
      default: "false"
  steps:
  - name: run-kubectl
    image: quay.io/kmcdermo/k8s-kubectl:latest
    workingDir: /workspace/source
    command: ["kubectl"]
    args:
    - "apply"
    - "--dry-run=$(inputs.params.DRYRUN)"
    - "-f"
    - "$(inputs.params.PATHTODEPLOYMENT)"