apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: toolchain-cicd-dry-run-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  params:
  - name: repo
    type: string
  - name: commit-sha
    type: string
  - name: namespace-name
    type: string
  tasks:

  - name: create-pending-status
    taskRef:
      name: create-github-status-task
    params:
    - name: repo
      value: $(params.repo)
    - name: commit-sha
      value: $(params.commit-sha)
    - name: state
      value: "pending"
    - name: description
      value: "Starting toolchain-cicd-dry-run-pipeline"
    - name: context
      value: "toolchain-cicd-dry-run-pipeline"

  # create/apply yaml files

  - name: apply-sync-directory
    taskRef:
      name: apply-resources-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    params:
    - name: path-to-deployment
      value: sync
    - name: namespace-name
      value: $(params.namespace-name)

  - name: apply-toolchain-pipeline-directory
    taskRef:
      name: apply-resources-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    params:
    - name: path-to-deployment
      value: toolchain-pipeline
    - name: namespace-name
      value: $(params.namespace-name)
    runAfter:
    - apply-sync-directory

  - name: apply-toolchain-cd-pipeline
    taskRef:
      name: process-project-and-apply-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    params:
    - name: path-to-deployment
      value: toolchain-pipeline/pipeline/toolchain-cd-pipeline.yaml
    - name: namespace-name
      value: $(params.namespace-name)
    runAfter:
    - apply-toolchain-pipeline-directory

  - name: apply-webhook-directory
    taskRef:
      name: apply-resources-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    params:
    - name: path-to-deployment
      value: webhook
    - name: namespace-name
      value: $(params.namespace-name)
    runAfter:
    - apply-sync-directory

  - name: ensure-webhooks
    taskRef:
      name: process-all-projects-and-create-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    params:
    - name: path-to-deployment
      value: webhook/pipeline-run/pipeline-run.yaml
    - name: namespace-name
      value: $(params.namespace-name)
    runAfter:
    - apply-webhook-directory

  - name: create-success-status
    taskRef:
      name: create-github-status-task
    runAfter:
    - build-image
    params:
    - name: repo
      value: $(params.repo)
    - name: commit-sha
      value: $(params.commit-sha)
    - name: state
      value: "success"
    - name: description
      value: "Completed toolchain-cicd-dry-run-pipeline"
    - name: context
      value: "toolchain-cicd-dry-run-pipeline"