apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: update-from-master-template
spec:
  params:
  - name: gitref
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: update-from-master-sync-$(uid)
    spec:
      serviceAccountName: toolchain-cd-sync-sa
      taskRef:
        name: toolchain-cd-sync-task
      inputs:
        params:
        - name: PATHTODEPLOYMENT
          value: sync
        resources:
        - name: source
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.gitref)
            - name: url
              value: $(params.gitrepositoryurl)

#  todo - use as pipelinerun - both of them to be able to update steps/tasks before upding the toolchain-pipeline resources

  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: update-from-master-toolchain-pipeline-$(uid)
    spec:
      serviceAccountName: toolchain-cd-sync-sa
      taskRef:
        name: toolchain-cd-sync-task
      inputs:
        params:
        - name: PATHTODEPLOYMENT
          value: toolchain-pipeline
        resources:
        - name: source
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.gitref)
            - name: url
              value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: update-from-master-webhooks-$(uid)
    spec:
      serviceAccountName: toolchain-cd-sync-sa
      taskRef:
        name: toolchain-cd-sync-task
      inputs:
        params:
        - name: PATHTODEPLOYMENT
          value: webhook
        resources:
        - name: source
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.gitref)
            - name: url
              value: $(params.gitrepositoryurl)
              
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: create-toolchain-cd-webhook-run-$(uid)
    spec:
      taskRef:
        name: create-webhook
      inputs:
        params:
        - name: GitHubOrg
          value: "matousjobanek"
        - name: GitHubRepo
          value: "toolchain-cd"
        - name: GitHubSecretName
          value: webhook-secret
        - name: GitHubAccessTokenKey
          value: token
        - name: GitHubUserKey
          value: user
        - name: GitHubSecretStringKey
          value: secret
        - name: ExternalDomain
          value: http://toolchain-cd-sync-eventlistener-toolchain-cd.apps.alkazako-20200212.devcluster.openshift.com
      timeout: 1000s
      serviceAccountName: tekton-triggers-createwebhook

  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: create-host-operator-webhook-run-$(uid)
    spec:
      taskRef:
        name: create-webhook
      inputs:
        params:
        - name: GitHubOrg
          value: "matousjobanek"
        - name: GitHubRepo
          value: "host-operator"
        - name: GitHubSecretName
          value: webhook-secret
        - name: GitHubAccessTokenKey
          value: token
        - name: GitHubUserKey
          value: user
        - name: GitHubSecretStringKey
          value: secret
        - name: ExternalDomain
          value: http://toolchain-cd-eventlistener-toolchain-cd.apps.alkazako-20200212.devcluster.openshift.com
      timeout: 1000s
      serviceAccountName: tekton-triggers-createwebhook

  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: create-member-operator-webhook-run-$(uid)
    spec:
      taskRef:
        name: create-webhook
      inputs:
        params:
        - name: GitHubOrg
          value: "matousjobanek"
        - name: GitHubRepo
          value: "member-operator"
        - name: GitHubSecretName
          value: webhook-secret
        - name: GitHubAccessTokenKey
          value: token
        - name: GitHubUserKey
          value: user
        - name: GitHubSecretStringKey
          value: secret
        - name: ExternalDomain
          value: http://toolchain-cd-eventlistener-toolchain-cd.apps.alkazako-20200212.devcluster.openshift.com
      timeout: 1000s
      serviceAccountName: tekton-triggers-createwebhook