apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: ${TOOLCHAIN_REPO}-cd
  spec:
    workspaces:
    - name: shared-workspace
    params:
    - name: repo-url
      type: string
    - name: repo-name
      type: string
    - name: repo-path
      description: Path to the repo
    - name: repo-revision
      description: The git revision
    - name: quay-namespace
      description: The quay namespace CSV should be pushed to
      default: codeready-toolchain

    - name: tools-image-url
      type: string
    - name: binary-image-url
      type: string

    tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace
      params:
      - name: url
        value: $(params.repo-url)
      - name: subdirectory
        value: $(params.repo-path)
      - name: revision
        value: $(params.repo-revision)
      - name: depth
        value: "0"

    - name: build-tools-image
      taskRef:
        name: build-docker-tools-image
      workspaces:
      - name: source
        workspace: shared-workspace
      params:
      - name: repo-path
        value: $(params.repo-path)
      - name: tools-image-url
        value: $(params.tools-image-url)
      runAfter:
      - fetch-repository

    - name: build-project
      taskRef:
        name: build-project
      workspaces:
      - name: source
        workspace: shared-workspace
      params:
      - name: repo-path
        value: $(params.repo-path)
      - name: repo-revision
        value: $(params.repo-revision)
      - name: tools-image-url
        value: $(params.tools-image-url)
      - name: binary-image-url
        value: $(params.binary-image-url)
      runAfter:
      - build-tools-image

    - name: generate-and-push-csv
      taskRef:
        name: generate-and-push-csv
      workspaces:
      - name: source
        workspace: shared-workspace
      params:
      - name: repo-path
        value: $(params.repo-path)
      - name: quay-namespace
        value: $(params.quay-namespace)
      - name: repo-revision
        value: $(params.repo-revision)
      - name: tools-image-url
        value: $(params.tools-image-url)
      runAfter:
      - build-project
parameters:
- name: TOOLCHAIN_REPO
  required: true
